### PR TITLE
Fix Invalid argument supplied for foreach

### PR DESCRIPTION
**Pull request by mwjames**

### CODE REVIEW

**Comment by mwjames** [comment]
By simply adding`<info />` to a page you get:

```
Warning: Invalid argument supplied for foreach() in ...\vendor\param-processor\param-processor\src\Processor.php on line 315

Notice: Undefined index: message in ...\extensions\SemanticMediaWiki\src\ParserFunctions\InfoParserFunction.php on line 35

Fatal error: Call to a member function getValue() on null in ...\extensions\SemanticMediaWiki\src\ParserFunctions\InfoParserFunction.php on line 35
```

**Comment by mwjames** [comment]
http://sandbox.semantic-mediawiki.org/w/index.php?title=ParamProcessorEmpty

**Comment by mwjames** [comment]
> Fatal error: Call to a member function getValue() on null in ...\extensions\SemanticMediaWiki\src\ParserFunctions\InfoParserFunction.php on line 35

Fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1608

**Comment by JeroenDeDauw** [comment]
Thanks

**Comment by JeroenDeDauw** [comment]
Released as 1.2.5

**Pull request merged**
